### ISSUE TITLE
Looks like tweets have stop posting to Facebook beginning in early May 2015

### ISSUE THREAD

**Issue by MarkRH** [andyyoung/Selective-Tweets#4]
I think Facebook changed some things that have broken this app. No idea if anyone even updates this thing now. Folks have been posting on the Selective Tweets Facebook page.

**Comment by MttCastelli** [comment]
+1. Can we know more? I miss this app.

regards

**Comment by andyyoung** [comment]
If anyone would like to fix the app to work with the new Facebook API and submit a patch, I'll be glad to merge and update. Otherwise, I'm trying to find time to fix it as soon as I can - unsure how the latest API may affect the functionality though.

**Comment by bsimser** [comment]
I'll see if I can get in and fix it and send a pull request. Like this tool, stopped working for me a few weeks back.

**Comment by MarkRH** [comment]
Well, it seems to be working again: https://www.facebook.com/selectivetwitter/posts/846574222085030

So, I'll mark my issue here closed.
